language: node_js
node_js:
  - "9.2"
env:
  global:
    secure: aRYNushLAVp1DFt0alD26QfK+HneAi1g/rXlivr8gXgEBm8i/glNRlXmSg3cWCK8gpnohO1v3V6wXXlHkesI6zr41tQD0qx9avQi8buCHyhB2jsibf74BMt5uF5n3wnXfweVYIRqQ0xxWYK4GVQtrOeYj3JsAh/LOsssyq6wIs2mDYKvbRASKqOXYRZkwNsdznpasLuBAuiea9SVhM9gbj8CThd9BaxqVFGRfp6ndTv3y11TON6uTLrxbB90LcGwKsxiNJcYoDQIveHQpP8vQ9TGxrGJhuMlRpNW5iHvcQ63zVHty6CnskrjtauYXdEqnXTHkCHZc0jifnYmyMPZidRrX/gQo4XVwem1wpzOHnQe76EfUVOCLjgqTcnofJaqMfDXBD+v4H/ux82J8hI8B0bDafdayzMyiZtV7EcioPGGOI/5ga0cyqIoTvzuFwq/7IDScGX4gn82J8xVwgp9POlZFpwjHz4UjtY0UXQqRar8MQb5/xWPHeiL3vVG3T9NDyQjvMqrbknqVPSvLfcMVa3VEv5ZunZN0Lr1PsmOWunXuJi6+5v5wx9iZpTb40wiZAozWbLEJ7PmShWtaDGU6FKyC7UMbIfdFoFHOTtPWGvHWoPbGPKe3tGpH7J9wty+8HDJRjybamchaO2wbRlrxGtIlUQLfSPBxbNE5GHeCzY=
